name: Build and Deploy

on:
  push:
    branches:
      - qybl  # 指定分支，例如 'qybl'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub  4.58
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 for building the project
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the JAR file using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}  # 使用环境变量传递区域
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 确保设置 AWS 凭据
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # 确保设置 AWS 凭据

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }} .

      # Step 6: Push Docker image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}